app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/* Admin Authentication routes */
Route::group(['prefix' => 'admin', 'before' => 'auth.admin'], function()
{
	Route::any('/', 'App\Controllers\Admin\DashboardController@index');
	Route::get('dashboard',['as'=>'admin.dashboard', 'uses'=>'App\Controllers\Admin\DashboardController@index']);
/*
	Route::get('admin/settings', array('as' => 'admin.settings', function(){
		$user = Sentry::getUser();

		return View::make('admin.settings')
			->with('user', $user);
	}));
	Route::get('admin/settings', array('as' => 'admin.settings.updateInfo', function(){
		Notification::success('Information changed succesfully.');
		$user = Sentry::getUser();

		return View::make('admin.settings')
			->with('user', $user);
	}));
*/
	Route::get('user', array('as'=>'admin.user','uses' => 'App\Controllers\Admin\UsersController@showUser'));
	Route::put('user', array('as'=>'admin.user.update','uses' => 'App\Controllers\Admin\UsersController@update'));

	Route::resource('articles', 'App\Controllers\Admin\ArticlesController');
	Route::resource('pages', 'App\Controllers\Admin\PagesController');
	Route::resource('categories', 'App\Controllers\Admin\CategoriesController');
});

Route::resource('comments', 'App\Controllers\CommentsController');

Route::get('admin/logout', ['as' => 'admin.logout', 'uses' => 'App\Controllers\Admin\AuthController@getLogout']);
Route::get('admin/login', ['as' => 'admin.login', 'uses' => 'App\Controllers\Admin\AuthController@getLogin']);
Route::post('admin/login', ['as' => 'admin.login.post', 'uses' => 'App\Controllers\Admin\AuthController@postLogin']);

app/views/admin/dashboard.blade.php
@extends('admin._layouts.default')

@section('main')

@include('admin._partials.category-create-modal')
@include('admin._partials.article-modal')

<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Dashboard</h1>
		@include('admin._partials.notifications')
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-8">
		<!-- Quick post panel -->
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-plus fa-fw"></i> Quick Post
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-12">
						@include('admin._partials.article-form')
					</div>
				</div>
				<!-- /.row (nested) -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-8 -->
	
	<div class="col-lg-4">
		<!-- Notifications panel -->
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-bell fa-fw"></i> Notifications Panel
			</div>
			<div class="panel-body">
				<div class="list-group">
					<div class="list-group-item">
						<i class="fa fa-comment fa-fw"></i> {{ count($newComments) }} New Comments
						<span class="pull-right text-muted small"><em>within 24h</em>
						</span>
					</div>
				</div>
			</div>
		</div>
		<!-- Newest posts panel -->
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-edit fa-fw"></i> Newest Posts
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="table-responsive">
				@if (count($articles) > 0)
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Title</th>
								<th>Updated</th>
								<th><i class="fa fa-cog fa-fw"></i></th>
							</tr>
						</thead>
						<tbody>
							{{-- Create table data for all posts --}}
							@foreach ($articles as $i => $article)
								<tr>
									<td><a data-toggle="modal" data-target="#myModal{{$i}}">{{ $article->title }}</a></td>
									<td>{{ $article->updated_at }}</td>
									<td>
										<a class="btn btn-success btn-xs" href="{{ URL::route('admin.articles.edit', $article->id) }}">Edit</a>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				@else
					<div class="well">
						<h5 class="text-center">
							No posts yet, create one!
							<hr>
							<a href="{{ URL::route('admin.articles.create') }}" class="btn btn-success"><i class="fa fa-plus-square-o fa-fw"></i> Add new post</a>
						</h5>							
					</div>
				@endif
				</div>
				<!-- /.table-responsive -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
		<!-- Pages panel -->
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-files-o fa-fw"></i> Pages
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="table-responsive">
				@if (count($pages) > 0)
					<table class="table table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Title</th>
								<th>Updated</th>
								<th><i class="fa fa-cog fa-fw"></i></th>
							</tr>
						</thead>
						<tbody>
							{{-- Create table data for all pages --}}
							@foreach ($pages as $page)
								<tr>
									<td>{{ $page->id }}</td>
									{{-- Creates URL to the specific page --}}
									<td><a href="{{ URL::route('admin.pages.show', $page->id) }}">{{ $page->title }}</a></td>
									<td>{{ $page->updated_at }}</td>
									<td>
										<a class="btn btn-success btn-xs" href="{{ URL::route('admin.pages.edit', $page->id) }}">Edit</a>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				@else
					<div class="well">
						<h5 class="text-center">
							No pages yet, create one!
							<hr>
							<a href="{{ URL::route('admin.pages.create') }}" class="btn btn-success"><i class="fa fa-plus-square-o fa-fw"></i> Create a new page</a>
						</h5>							
					</div>
				@endif
				</div>
				<!-- /.table-responsive -->
			</div>
			<!-- /.panel-body -->
		</div>
		<!-- /.panel -->
	</div>
	<!-- /.col-lg-4 -->
</div>
<!-- /.row -->
@stop
@section('scripts')

<script src="{{ URL::asset('ckeditor/ckeditor.js') }}"></script>
<script>
	// Replace the <textarea id="editor-area"> with a CKEditor
	// instance, using default configuration.
	CKEDITOR.replace( 'editor-area', {
		toolbar: 'Basic',
		uiColor: '#DDDDDD'
	});
</script>
@stop

app/views/admin/settings.blade.php
@extends('admin._layouts.default')

@section('main')

<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Edit your personal information <a href="{{ URL::route('admin.dashboard') }}" class="btn btn-default">Return</a></h1>
	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		@include('admin._partials.notifications')

		{{ Form::model($user, ['method' => 'put', 'route' => 'admin.user.update']) }}
			<div class="form-group">
				{{ Form::label('first_name', 'First name *') }}
				{{ Form::text('first_name', null, array('class'=>'form-control','placeholder'=>'Enter your first name')) }}
			</div>
			<div class="form-group">
				{{ Form::label('last_name', 'Surname *') }}
				{{ Form::text('last_name', null, array('class'=>'form-control','placeholder'=>'Enter your surname')) }}
			</div>
			<div class="form-group">
				{{ Form::label('email', 'Email *') }}
				{{ Form::email('email', null, array('class'=>'form-control','placeholder'=>'Enter your surname')) }}
			</div>
			<p class="text-muted">* required fields</p>
			{{ Form::submit('Submit', ['class' => 'btn btn-success']) }}
			<a href="{{ URL::route('admin.dashboard') }}" class="btn btn-danger"><i class="fa fa-times-circle fa-fw"></i> Cancel</a>
		{{ Form::close() }}

	</div>
	<!-- /.col-lg-12 -->
</div>
<!-- /.row -->

@stop