app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/* Admin Authentication routes */
Route::group(['prefix' => 'admin', 'before' => 'auth.admin'], function()
{
	Route::any('/', 'App\Controllers\Admin\DashboardController@index');
	Route::get('dashboard',['as'=>'admin.dashboard', 'uses'=>'App\Controllers\Admin\DashboardController@index']);
/*
	Route::get('admin/settings', array('as' => 'admin.settings', function(){
		$user = Sentry::getUser();

		return View::make('admin.settings')
			->with('user', $user);
	}));
	Route::get('admin/settings', array('as' => 'admin.settings.updateInfo', function(){
		Notification::success('Information changed succesfully.');
		$user = Sentry::getUser();

		return View::make('admin.settings')
			->with('user', $user);
	}));
*/
	Route::get('user', array('as'=>'admin.user','uses' => 'App\Controllers\Admin\UsersController@showUser'));
	Route::put('user', array('as'=>'admin.user.update','uses' => 'App\Controllers\Admin\UsersController@update'));

	Route::resource('articles', 'App\Controllers\Admin\ArticlesController');
	Route::resource('pages', 'App\Controllers\Admin\PagesController');
	Route::resource('categories', 'App\Controllers\Admin\CategoriesController');
});

Route::resource('comments', 'App\Controllers\CommentsController');

Route::get('admin/logout', ['as' => 'admin.logout', 'uses' => 'App\Controllers\Admin\AuthController@getLogout']);
Route::get('admin/login', ['as' => 'admin.login', 'uses' => 'App\Controllers\Admin\AuthController@getLogin']);
Route::post('admin/login', ['as' => 'admin.login.post', 'uses' => 'App\Controllers\Admin\AuthController@postLogin']);

app/views/admin/_partials/article-form.blade.php
{{-- Open Form to prepare for saving new page --}}
{{-- Don't need to define HTTP method, Form functions via POST --}}
{{ Form::open(array('route'=>'admin.articles.store', 'files'=>true)) }}
	<div class="form-group">
		{{ Form::label('title', 'Title *') }}
		{{ Form::text('title', null, array('class'=>'form-control','placeholder'=>'Enter title')) }}
	</div>
	<div class="form-group">
		{{ Form::label('image', 'Image') }}<br>
		{{-- fileinput from Jasny's Bootstrap --}}
		<div class="fileinput fileinput-new" data-provides="fileinput">
			<div class="fileinput-new thumbnail" style="width: 200px;">
				<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image">
			</div>
			<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px;"></div>
			<div>
				<span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>{{ Form::file('image') }}</span>
				<a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
			</div>
		</div>
	</div>
	<div class="form-group">
		{{ Form::label('body', 'Description') }}
		{{ Form::textarea('body', null, array('id'=>'editor-area','class'=>'form-control','rows'=>'5')) }}
	</div>
	<div class="form-group">
		{{ Form::label('category', 'Category *') }}
		{{ Form::select('category', $categories, null, array('class' => 'form-control')); }}
		<br>
		<a class="btn btn-default" data-toggle="modal" data-target="#categoryModal">Add new category</a>
	</div>
	<p class="text-muted">* required fields</p>
	{{ Form::submit('Submit', ['class' => 'btn btn-success']) }}
	{{ Form::reset('Reset', ['class' => 'btn btn-default']) }}
{{ Form::close() }}

app/views/admin/_partials/article-modal.blade.php
<!-- Article View Modal -->
@foreach ($articles as $i => $article)
<div class="modal fade" id="myModal{{$i}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">{{ $article->title }}</h4>
			</div>
			<!-- /.modal-header -->
			<div class="modal-body">
				@if ($article->image)
					<img class="img-responsive" src="{{ Image::resize($article->image, 858, 643.5) }}" alt="">
				@endif
				@if ($article->body)
					<hr>
					{{ $article->body }}
				@endif
			</div>
			<!-- /.modal-body -->
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<a href="{{ URL::route('admin.articles.edit', $article->id) }}" class="btn btn-success btn-mini pull-left">Edit</a>
			</div>
			<!-- /.modal-footer -->
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->
@endforeach

app/views/admin/_partials/category-create-modal.blade.php
<!-- Category creation modal -->
<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="categoryModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="categoryModalLabel">Add new category</h4>
			</div>
			<!-- /.modal-header -->
			<div class="modal-body">
				{{ Notification::showError() }}
				{{ Notification::showInfo() }}
				{{ Notification::showWarning() }}

				{{-- Open Form to prepare for saving new page --}}
				{{-- Don't need to define HTTP method, Form functions via POST --}}
				{{ Form::open(array('route'=>'admin.categories.store')) }}

					<div class="form-group">
						{{ Form::label('category', 'Name') }}
						{{ Form::text('category', null, array('class'=>'form-control','placeholder'=>'Enter a name for the category')) }}
					</div>
			</div>
			<!-- /.modal-body -->
			<div class="modal-footer">					
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					{{ Form::submit('Submit', array('class' => 'btn btn-success')) }}

				{{ Form::close() }}
			</div>
			<!-- /.modal-footer -->
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/admin/_partials/category-modal.blade.php
<!-- Category Modal -->
@foreach ($categories as $i => $category)
<div class="modal fade" id="myModal{{$i}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 class="modal-title" id="myModalLabel">Edit category</h3>
			</div>
			<!-- /.modal-header -->
			<div class="modal-body">
				{{ Form::model($category, array('method' => 'put', 'route' => array('admin.categories.update', $category->id))) }}

					<div class="form-group">
						{{ Form::label('category', 'Name') }}
						{{ Form::text('category', null, array('class'=>'form-control','placeholder'=>'Enter name for category')) }}
					</div>
			</div>
			<!-- /.modal-body -->
			<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					{{ Form::submit('Save', array('class' => 'btn btn-success')) }}
				{{ Form::close() }}
			</div>
			<!-- /.modal-footer -->
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->
@endforeach

app/views/admin/_partials/navbar.blade.php
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="{{ URL::route('admin.dashboard') }}">Demo blog - Control Panel</a>
	</div>
	<!-- /.navbar-header -->

	<ul class="nav navbar-top-links navbar-right">
		<li>
			<a href="{{ URL('/') }}">
				<i class="fa fa-desktop fa-fw"></i> Site</i>
			</a>
		</li>
		<li class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#">
				<i class="fa fa-user fa-fw"></i> User <i class="fa fa-caret-down"></i>
			</a>
			<ul class="dropdown-menu dropdown-user">
				<li><a href="{{ URL::route('admin.user') }}"><i class="fa fa-user fa-fw"></i> User Profile</a>
				</li>
				<li class="divider"></li>
				<li><a href="{{ URL::route('admin.logout') }}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
				</li>
			</ul>
			<!-- /.dropdown-user -->
		</li>
		<!-- /.dropdown -->
	</ul>
	<!-- /.navbar-top-links -->

	<div class="navbar-default navbar-static-side" role="navigation">
		<div class="sidebar-collapse">
			<ul class="nav" id="side-menu">
				</li>
				<li class="{{ Request::is('admin/dashboard') ? 'active' : null }}">
					<a href="{{ URL::route('admin.dashboard') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
				</li>
				<li class="{{ Request::is('admin/articles*') ? 'active' : null }}">
					<a href="{{ URL::route('admin.articles.index') }}"><i class="fa fa-edit fa-fw"></i> Posts</a>
				</li>
				<li class="{{ Request::is('admin/categories*') ? 'active' : null }}">
					<a href="{{ URL::route('admin.categories.index') }}"><i class="fa fa-inbox fa-fw"></i> Categories</a>
				</li>
				<!--
				<li>
					<a href="tables.html"><i class="fa fa-comments-o fa-fw"></i> Comments</a>
				</li>
				-->
				<li class="{{ Request::is('admin/pages*') ? 'active' : null }}">
					<a href="{{ URL::route('admin.pages.index') }}"><i class="fa fa-files-o fa-fw"></i> Pages</a>
				</li>
				<!--
				<li>
					<a href="forms.html"><i class="fa fa-eye fa-fw"></i> Appearance</a>
				</li>
				<li>
					<a href="forms.html"><i class="fa fa-cog fa-fw"></i> Settings</a>
				</li>
				-->
			</ul>
			<!-- /#side-menu -->
		</div>
		<!-- /.sidebar-collapse -->
	</div>
	<!-- /.navbar-static-side -->
</nav>

app/views/admin/_partials/notifications.blade.php
{{ Notification::showAll() }}

@if ($errors->any())
	<div class="alert alert-danger">
		{{ implode('<br>', $errors->all()) }}
	</div>
@endif